version: '2'

services:
  squid:
    build: "."
    ports:
      - "3128:3128"
    environment:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
    volumes:
      - squid-cache:/var/spool/squid3

volumes:
  squid-cache:
